export const customerTestimonials = [
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },

    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
    {
        postId: 1,
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        body: "The booking process was seamless, and the facility was well-maintained. Highly recommend!",
    },
    {
        postId: 2,
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        body: "Great experience! The customer service was exceptional, and the facilities were top-notch.",
    },
    {
        postId: 3,
        id: 3,
        name: "Michael Lee",
        email: "michael.lee@example.com",
        body: "I had a wonderful time using the sports facility. The booking system is easy to use, and the staff is very helpful.",
    },
    {
        postId: 4,
        id: 4,
        name: "Emily Johnson",
        email: "emily.johnson@example.com",
        body: "Highly impressed with the facilities and services. Booking was hassle-free, and everything was well-organized.",
    },
    {
        postId: 5,
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        body: "A fantastic experience! The facilities were clean, and the booking system made it easy to secure a spot.",
    },
];
